/** FIFA World Cup 2026–inspired palette (host nations + official brand tones). */
export const WC_BRAND = {
  green: '#00A651',
  gold: '#FFB81C',
  navy: '#00205B',
  coral: '#E31837',
  sky: '#00A3E0',
  magenta: '#9B2C8B',
  cream: '#FFF9ED',
  pitch: '#1B7A45',
} as const;

const tintColorLight = WC_BRAND.green;
const tintColorDark = '#4ADE80';

export default {
  light: {
    text: WC_BRAND.navy,
    background: WC_BRAND.cream,
    tint: tintColorLight,
    tabIconDefault: '#8A9BA8',
    tabIconSelected: tintColorLight,
    card: '#FFFFFF',
    border: '#D4E4DA',
    muted: '#5C6B7A',
    accent: WC_BRAND.gold,
    success: WC_BRAND.pitch,
    danger: WC_BRAND.coral,
    live: WC_BRAND.coral,
    brandNavy: WC_BRAND.navy,
    brandGold: WC_BRAND.gold,
    brandSky: WC_BRAND.sky,
    brandCoral: WC_BRAND.coral,
    brandGreen: WC_BRAND.green,
    heroGradientStart: WC_BRAND.navy,
    heroGradientEnd: WC_BRAND.pitch,
    stripe1: WC_BRAND.green,
    stripe2: WC_BRAND.gold,
    stripe3: WC_BRAND.coral,
    stripe4: WC_BRAND.sky,
    highlightBg: '#E8F8EE',
    pointsBg: '#FFF4D6',
  },
  dark: {
    text: '#F8FAFC',
    background: '#0A1628',
    tint: tintColorDark,
    tabIconDefault: '#64748B',
    tabIconSelected: tintColorDark,
    card: '#122035',
    border: '#1E3A5F',
    muted: '#94A3B8',
    accent: WC_BRAND.gold,
    success: '#4ADE80',
    danger: '#FB7185',
    live: '#FF6B6B',
    brandNavy: '#0D2847',
    brandGold: WC_BRAND.gold,
    brandSky: WC_BRAND.sky,
    brandCoral: WC_BRAND.coral,
    brandGreen: tintColorDark,
    heroGradientStart: '#0A1628',
    heroGradientEnd: '#0F2D1F',
    stripe1: WC_BRAND.green,
    stripe2: WC_BRAND.gold,
    stripe3: WC_BRAND.coral,
    stripe4: WC_BRAND.sky,
    highlightBg: '#0F2D22',
    pointsBg: '#2A2210',
  },
};

export type ThemeColors = typeof import('./Colors').default.light;
